### ISSUE TITLE
Implement SubnetFromState

### ISSUE THREAD

**Issue by goncalo-rodrigues** [multycloud/multy#216]
Read attributes from internal terraform state and convert to object as per https://github.com/multycloud/multy/blob/main/resources/types/virtual_network.go#L65

**Comment by ksankeerth** [comment]
Hi @goncalo-rodrigues/ @JCoelhoo ,
I'm new to multy. Can I try to fix this issue?

**Comment by goncalo-rodrigues** [comment]
Yea of course! Let me know if you need help getting started or just message me on discord with any question

**Comment by goncalo-rodrigues** [comment]
Hey @ksankeerth, I was wondering if you need help getting started with the codebase? Feel free to join us on discord at https://multy.dev/discord
