### ISSUE TITLE
Support GCP resources

### ISSUE THREAD

**Issue by goncalo-rodrigues** [multycloud/multy#261]

**Comment by mattvella07** [comment]
@goncalo-rodrigues I imagine there's a lot to do here, but I could try to get started.  Would it be best to start by adding a GCP option to cloud providers and adding the regions and AZs?

**Comment by goncalo-rodrigues** [comment]
Yea, this is just an umbrella item. We will break it down into smaller chunks over the next month and then you can pick up some of the items, so I wouldn't get started just yet.
In the meantime, if you want to contribute more, we added a few validation issues recently, or if you want something more challenging, there's
Adding tags to resources (#190 )
Adding more overrides (#205) - we added sizes for vms and kubernetes node pools, you can add ami overrides for example. Locations will be a bit harder

If there's anything else you think needs work, you can also just add an issue!
