### ISSUE TITLE
Validate virtual_network resource

### ISSUE THREAD

**Issue by goncalo-rodrigues** [multycloud/multy#267]
- Check that the CIDR block is valid
- Check that the name matches the restrictions in https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

Matching issue in terraform provider: https://github.com/multycloud/terraform-provider-multy/issues/54

**Comment by szymonnogiec** [comment]
@goncalo-rodrigues Given that you did CIDR validation and I've implemented name validation in the  https://github.com/multycloud/multy/pull/376 this should be closed I think.

**Comment by goncalo-rodrigues** [comment]
Yap, you're right.
