### ISSUE TITLE
Validate network security group resource

### ISSUE THREAD

**Issue by goncalo-rodrigues** [multycloud/multy#271]
- Check that name matches azure's restrictions: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules
- Check that security rules have a valid port range
- Check that security rules cidr block is valid
- Check that security rules protocl is valid (check possible values https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_rule)
- Check that priority is between 100 and 4096

**Comment by szymonnogiec** [comment]
Hey, @goncalo-rodrigues please assign this to me, starting working on this now.

**Comment by szymonnogiec** [comment]
@goncalo-rodrigues This can be closed now.
