### ISSUE TITLE
Add mapping for GCP virtual machine sizes

### ISSUE THREAD

**Issue by goncalo-rodrigues** [multycloud/multy#345]
We only have mapping for general purpose compute, we're missing compute optimized and memory optimized for GCP.

Mapping is defined in https://github.com/multycloud/multy/blob/main/resources/common/vm_size.go

**Comment by szymonnogiec** [comment]
Hi, want to work on this next

**Comment by goncalo-rodrigues** [comment]
Perfect, I'll assign it to you!
