### ISSUE TITLE
Database fixes

### ISSUE THREAD

**Issue by goncalo-rodrigues** [multycloud/multy#68]
- Azure is not accessible publicly
- Aws is fine with username as the username, but azure expects username@host. Maybe they are using different database engines?

More details in test/e2e/database/database_test.go

**Comment by JCoelhoo** [comment]
Added AZ mysql firewall rule to match AWS https://github.com/multycloud/multy/pull/79
https://techcommunity.microsoft.com/t5/azure-database-for-mysql-blog/why-is-username-servername-required-to-connect-to-azure-database/ba-p/1204525
